maps: &maps
  map_tiles_provider: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_tiles_provider_attribution: "&copy; <a href=\"http://osm.org/copyright\">OpenStreetMap</a> contributors"

apis: &apis
  microsoft_api_key: <%= ENV["MICROSOFT_API_KEY"] %>
  census_api_end_point: <%= ENV["CENSUS_API_END_POINT"] %>
  census_api_institution_code: <%= ENV["CENSUS_API_INSTITUTION_CODE"] %>
  census_api_portal_name: <%= ENV["CENSUS_API_PORTAL_NAME"] %>
  census_api_user_code: <%= ENV["CENSUS_API_USER_CODE"] %>
  sms_account_sid: <%= ENV["SMS_ACCOUNT_SID"] %>
  sms_auth_token: <%= ENV["SMS_AUTH_TOKEN"] %>
  sms_phone_number: <%= ENV["SMS_PHONE_NUMBER"] %>

http_basic_auth: &http_basic_auth
  http_basic_auth: <%= ENV["HTTP_BASIC_AUTH"] %>

smtp_settings: &smtp_settings
  address: <%= ENV["SMTP_ADDRESS"] %>
  port: <%= ENV["SMTP_PORT"] %>
  domain: <%= ENV["SMTP_DOMAIN"] %>
  user_name: <%= ENV["SMTP_USERNAME"] %>
  password: <%= ENV["SMTP_PASSWORD"] %>
  authentication: <%= ENV["SMTP_AUTHENTICATION"] %>
  enable_starttls_auto: <%= ENV["SMTP_ENABLE_STARTTLS_AUTO"] %>

mailer: &mailer
  mailer_from_address: <%= ENV["MAILER_FROM_ADDRESS"] %>
  mailer_from_name: <%= ENV["MAILER_FROM_NAME"] %>

aws_s3_file_storage: &aws_s3_file_storage
  aws_s3_host_name: <%= ENV["AWS_S3_HOST_NAME"] %>
  aws_s3_access_key_id: <%= ENV["AWS_S3_ACCESS_KEY_ID"] %>
  aws_s3_secret_access_key: <%= ENV["AWS_S3_SECRET_ACCESS_KEY"] %>
  aws_s3_region: <%= ENV["AWS_S3_REGION"] %>
  aws_s3_bucket: <%= ENV["AWS_S3_BUCKET"] %>

settings: &settings
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  server_name: <%= ENV["SERVER_NAME"] %>
  rollbar_server_token: <%= ENV["ROLLBAR_SERVER_TOKEN"] %>
  http_basic_username: <%= ENV["HTTP_BASIC_USERNAME"] %>
  http_basic_password: <%= ENV["HTTP_BASIC_PASSWORD"] %>
  managers_url: <%= ENV["MANAGERS_URL"] %>
  managers_application_key: <%= ENV["MANAGERS_APPLICATION_KEY"] %>
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  google_oauth2_key: <%= ENV["GOOGLE_OAUTH2_KEY"] %>
  google_oauth2_secret: <%= ENV["GOOGLE_OAUTH2_SECRET"] %>
  force_ssl: <%= ENV["FORCE_SSL"] %>

production:
  <<: *settings
  <<: *apis
  <<: *http_basic_auth
  <<: *maps
  <<: *mailer
  <<: *aws_s3_file_storage
  smtp_settings:
    <<: *smtp_settings


staging:
  <<: *settings
  <<: *apis
  <<: *http_basic_auth
  <<: *maps
  <<: *mailer
  <<: *aws_s3_file_storage
  smtp_settings:
    <<: *smtp_settings

preproduction:
  <<: *settings
  <<: *apis
  <<: *http_basic_auth
  <<: *maps
  <<: *mailer
  <<: *aws_s3_file_storage
  smtp_settings:
    <<: *smtp_settings

default: &default
  secret_key_base: 56792feef405a59b18ea7db57b4777e855103882b926413d4afdfb8c0ea8aa86ea6649da4e729c5f5ae324c0ab9338f789174cf48c544173bc18fdc3b14262e4
  email_interceptor_recipients: ""

development:
  <<: *default
  database: consul_development

test:
  <<: *default
  database: consul_test
